### ISSUE TITLE
[ta/Makefile][os_test_lib]: building os_test error when using -jN

### ISSUE THREAD

**Issue by omasse-linaro** [OP-TEE/optee_test#307]
Hi,

When using parallelization build, I get a link error when building os_test:  cannot find -los_test.
os_test is build before os_test_lib component as there seems to have no dependencies between them.

My ugly solution in Makefile is the following:
.PHONY: ta
ta: 
	$(q)$(foreach dir,$(OS_TEST_LIB), $(MAKE) -C $(dir) O=$(out-dir)/ta/$(dir) &&) true
	$(q)$(foreach dir,$(TA_DIRS), $(MAKE) -C $(dir) O=$(out-dir)/ta/$(dir) &&) true

Do you have a fix for that issue ?

King regards

**Comment by jforissier** [comment]
Hi @oley06 ,

I don't see how `os_test` would be built before `os_test_lib` (thus failing the dependency), because there is a `foreach` loop, which creates a sequential list of commands, and `$(OS_TEST_LIB)` comes before `os_test` in `TA_DIRS`.
In other words, the `foreach` loop should expand to:
```
make -C create_fail_test O=... && make -C crypt O=... && make -C os_test_lib O=... && make -c os_test O=... && ...
```

I'm puzzled.

**Comment by oley06** [comment]
You are right, in fact my issue is not with the Makefile but with ta/Android.mk.

include $(call all-makefiles-under, $(LOCAL_PATH))

the ninja build system is building all the ta including the os_test_lib in parallel.

**Comment by jforissier** [comment]
I don't know much about the Android build and even less about ninja :(

Isn't this supposed to deal with the dependency? https://github.com/OP-TEE/optee_test/blob/3.2.0/ta/os_test/Android.mk#L5

@vchong any idea? I think I hear "ninja is not supported" already :))

**Comment by oley06** [comment]
I'm not familiar with Android build too, but how CFG_TA_DYNLINK is defined without included mk/conk.mk ?

**Comment by oley06** [comment]
@vchong  thanks for your reply, my platform is the imx 8mq from NXP.
my source tree is from tag 3.2.0 and get all the commit you mention.

I have added a warning log into optee_test/os_test/Android.mk to log the CFG_TA_DYNLINK value.
When building from scratch, the config value is empty. But when running a second time, I finally get CFG_TA_DYNLINK initiated with 'y' as defined in the conf.mk.

My issue is certainly due to a mistake in my environment.

**Comment by oley06** [comment]
as far as I understand, the ninja build system is parsing all the mk files before the build process.
all variables value are resolved at this stage.

as I build optee_os and optee_test at once, the TA_DEV_KIT_DIR cannot contain the necessary files for building TA when mk files are parsed.
then, when $(TA_DEV_KIT_DIR)/host_include/conf.mk is included in optee_test, nothing is found.

everything is working fine if optee_os is already built. thing that cannot not be true when building a full Android image on a build server.

**Comment by vchong** [comment]
It's not a mistake in your environment. It's a known limitation with the current build system, as explained in the link https://github.com/OP-TEE/optee_test/issues/275 given above. The details are the same as given in your analysis, which is correct.

**Comment by wamserma** [comment]
> I don't see how `os_test` would be built before `os_test_lib` (thus failing the dependency), because there is a `foreach` loop, which creates a sequential list of commands,

This uses globbing and sorting in globbing is dependent on the locale. While I cannot pinpoint the exact setting, I get different orderings when I run `echo ta/*/Makefile` on Ubuntu and in a nix-shell on that same Ubuntu machine.

As `os_test` already has a hack in its Makefile, I took the liberty (https://github.com/OP-TEE/optee_test/pull/373) to extend this hack to cover the build dependency. This will not help with Android or Ninja, but should be good enough for parallel builds with GNU make.

**Comment by wamserma** [comment]
I think this is still an issue since https://github.com/OP-TEE/build/pull/353 or sth. similar was not yet merged.
